import bcrypt from 'bcryptjs'
import type { Database } from './store.js'
import type { StoredUser } from './store.js'
import { DEMO_PASSWORD } from '../shared/constants.js'

const hash = bcrypt.hashSync(DEMO_PASSWORD, 8)

function user(
  partial: Omit<StoredUser, 'passwordHash' | 'appearance' | 'status'> & {
    appearance?: StoredUser['appearance']
    status?: StoredUser['status']
  },
): StoredUser {
  return {
    passwordHash: hash,
    appearance: 'system',
    status: 'active',
    ...partial,
  }
}

/** Anchored to 2026-08-18 (project "today") so relative copy stays stable. */
export const TODAY = '2026-08-18T08:00:00.000Z'

export function createSeed(): Database {
  const users: StoredUser[] = [
    user({
      id: 'user_david',
      email: 'david@luma.health',
      role: 'patient',
      firstName: 'David',
      lastName: 'Daniel',
      createdAt: '2025-11-02T10:00:00.000Z',
      lastActiveAt: '2026-08-18T07:40:00.000Z',
    }),
    user({
      id: 'user_sarah',
      email: 'sarah@luma.health',
      role: 'patient',
      firstName: 'Sarah',
      lastName: 'Miller',
      createdAt: '2025-09-14T10:00:00.000Z',
      lastActiveAt: '2026-08-17T16:10:00.000Z',
    }),
    user({
      id: 'user_james',
      email: 'james@luma.health',
      role: 'patient',
      firstName: 'James',
      lastName: 'Wilson',
      createdAt: '2026-01-20T10:00:00.000Z',
      lastActiveAt: '2026-08-12T11:00:00.000Z',
    }),
    user({
      id: 'user_leila',
      email: 'leila@luma.health',
      role: 'patient',
      firstName: 'Leila',
      lastName: 'Hassan',
      createdAt: '2026-03-08T10:00:00.000Z',
      lastActiveAt: '2026-08-15T09:20:00.000Z',
    }),
    user({
      id: 'user_amara',
      email: 'amara@luma.health',
      role: 'clinician',
      firstName: 'Amara',
      lastName: 'Okafor',
      createdAt: '2024-04-11T10:00:00.000Z',
      lastActiveAt: '2026-08-18T07:10:00.000Z',
    }),
    user({
      id: 'user_weber',
      email: 'weber@luma.health',
      role: 'clinician',
      firstName: 'Jonas',
      lastName: 'Weber',
      createdAt: '2024-08-22T10:00:00.000Z',
      lastActiveAt: '2026-08-17T18:40:00.000Z',
    }),
    user({
      id: 'user_chen',
      email: 'maya@luma.health',
      role: 'clinician',
      firstName: 'Maya',
      lastName: 'Chen',
      createdAt: '2025-02-03T10:00:00.000Z',
      lastActiveAt: '2026-08-16T14:00:00.000Z',
    }),
    user({
      id: 'user_adebayo',
      email: 'tunde@luma.health',
      role: 'clinician',
      firstName: 'Tunde',
      lastName: 'Adebayo',
      createdAt: '2025-06-19T10:00:00.000Z',
      lastActiveAt: '2026-08-18T06:50:00.000Z',
    }),
    user({
      id: 'user_admin',
      email: 'admin@luma.health',
      role: 'admin',
      firstName: 'Nora',
      lastName: 'Ellis',
      createdAt: '2024-01-08T10:00:00.000Z',
      lastActiveAt: '2026-08-18T07:55:00.000Z',
    }),
  ]

  return {
    users,
    patients: [
      {
        userId: 'user_david',
        dateOfBirth: '1994-03-12',
        sex: 'Male',
        phone: '+49 151 4400 2211',
        address: '18 Lindenstraße',
        city: 'Berlin',
        emergencyContact: {
          name: 'Hannah Daniel',
          relationship: 'Sister',
          phone: '+49 151 8800 1144',
        },
        preferredLanguage: 'English',
        notifications: {
          appointmentReminders: true,
          prescriptionUpdates: true,
          careTeamMessages: true,
        },
      },
      {
        userId: 'user_sarah',
        dateOfBirth: '1992-06-04',
        sex: 'Female',
        phone: '+49 176 2200 8833',
        address: '4 Gartenweg',
        city: 'Hamburg',
        emergencyContact: {
          name: 'Paul Miller',
          relationship: 'Partner',
          phone: '+49 176 2200 8890',
        },
        preferredLanguage: 'English',
        notifications: {
          appointmentReminders: true,
          prescriptionUpdates: true,
          careTeamMessages: true,
        },
      },
      {
        userId: 'user_james',
        dateOfBirth: '1986-11-21',
        sex: 'Male',
        phone: '+44 7700 900218',
        address: '22 Elm Court',
        city: 'Manchester',
        emergencyContact: {
          name: 'Ruth Wilson',
          relationship: 'Spouse',
          phone: '+44 7700 900219',
        },
        preferredLanguage: 'English',
        notifications: {
          appointmentReminders: true,
          prescriptionUpdates: false,
          careTeamMessages: true,
        },
      },
      {
        userId: 'user_leila',
        dateOfBirth: '1998-01-30',
        sex: 'Female',
        phone: '+33 6 12 44 90 18',
        address: '9 Rue des Lilas',
        city: 'Lyon',
        emergencyContact: {
          name: 'Omar Hassan',
          relationship: 'Father',
          phone: '+33 6 12 44 90 19',
        },
        preferredLanguage: 'French',
        notifications: {
          appointmentReminders: true,
          prescriptionUpdates: true,
          careTeamMessages: false,
        },
      },
    ],
    doctors: [
      {
        userId: 'user_amara',
        title: 'Dr.',
        specialty: 'Cardiology',
        bio: 'Dr. Okafor focuses on preventive cardiology and long-term heart health. She prefers unhurried conversations and clear next steps.',
        yearsExperience: 12,
        languages: ['English', 'German', 'Igbo'],
        consultationTypes: ['video', 'in-person'],
        verificationStatus: 'verified',
      },
      {
        userId: 'user_weber',
        title: 'Dr.',
        specialty: 'Family medicine',
        bio: 'A generalist with a calm, practical style. Dr. Weber helps people make sense of everyday symptoms before they become urgent.',
        yearsExperience: 16,
        languages: ['German', 'English'],
        consultationTypes: ['video', 'in-person'],
        verificationStatus: 'verified',
      },
      {
        userId: 'user_chen',
        title: 'Dr.',
        specialty: 'Dermatology',
        bio: 'Dr. Chen treats chronic skin conditions with a light, evidence-led approach and careful follow-up.',
        yearsExperience: 9,
        languages: ['English', 'French'],
        consultationTypes: ['video', 'in-person'],
        verificationStatus: 'verified',
      },
      {
        userId: 'user_adebayo',
        title: 'Dr.',
        specialty: 'Endocrinology',
        bio: 'Specialist in metabolic care, including diabetes and thyroid conditions. Clear plans, few surprises.',
        yearsExperience: 11,
        languages: ['English', 'Yoruba'],
        consultationTypes: ['video'],
        verificationStatus: 'pending',
      },
    ],
    availability: [
      { id: 'av_am_1', doctorId: 'user_amara', dayOfWeek: 1, start: '09:00', end: '12:00' },
      { id: 'av_am_2', doctorId: 'user_amara', dayOfWeek: 1, start: '14:00', end: '17:00' },
      { id: 'av_am_3', doctorId: 'user_amara', dayOfWeek: 2, start: '09:00', end: '13:00' },
      { id: 'av_am_4', doctorId: 'user_amara', dayOfWeek: 3, start: '09:30', end: '12:30' },
      { id: 'av_am_5', doctorId: 'user_amara', dayOfWeek: 4, start: '10:00', end: '16:00' },
      { id: 'av_am_6', doctorId: 'user_amara', dayOfWeek: 5, start: '09:00', end: '12:00' },
      { id: 'av_we_1', doctorId: 'user_weber', dayOfWeek: 1, start: '08:30', end: '12:30' },
      { id: 'av_we_2', doctorId: 'user_weber', dayOfWeek: 2, start: '08:30', end: '15:00' },
      { id: 'av_we_3', doctorId: 'user_weber', dayOfWeek: 4, start: '09:00', end: '17:00' },
      { id: 'av_ch_1', doctorId: 'user_chen', dayOfWeek: 2, start: '10:00', end: '16:00' },
      { id: 'av_ch_2', doctorId: 'user_chen', dayOfWeek: 3, start: '10:00', end: '16:00' },
      { id: 'av_ch_3', doctorId: 'user_chen', dayOfWeek: 5, start: '09:00', end: '13:00' },
      { id: 'av_ad_1', doctorId: 'user_adebayo', dayOfWeek: 1, start: '13:00', end: '17:00' },
      { id: 'av_ad_2', doctorId: 'user_adebayo', dayOfWeek: 3, start: '09:00', end: '13:00' },
      { id: 'av_ad_3', doctorId: 'user_adebayo', dayOfWeek: 5, start: '13:00', end: '17:00' },
    ],
    appointments: [
      {
        id: 'apt_david_amara',
        patientId: 'user_david',
        doctorId: 'user_amara',
        startsAt: '2026-08-19T10:30:00.000Z',
        endsAt: '2026-08-19T11:00:00.000Z',
        type: 'video',
        reason: 'Follow-up after recent blood pressure readings',
        status: 'confirmed',
        createdAt: '2026-08-18T08:42:00.000Z',
      },
      {
        id: 'apt_david_past',
        patientId: 'user_david',
        doctorId: 'user_weber',
        startsAt: '2026-07-22T09:00:00.000Z',
        endsAt: '2026-07-22T09:30:00.000Z',
        type: 'in-person',
        reason: 'Annual check-in',
        status: 'completed',
        createdAt: '2026-07-10T11:00:00.000Z',
      },
      {
        id: 'apt_sarah_today',
        patientId: 'user_sarah',
        doctorId: 'user_amara',
        startsAt: '2026-08-18T10:30:00.000Z',
        endsAt: '2026-08-18T11:00:00.000Z',
        type: 'video',
        reason: 'Follow-up consultation',
        status: 'confirmed',
        createdAt: '2026-08-12T09:00:00.000Z',
      },
      {
        id: 'apt_james_today',
        patientId: 'user_james',
        doctorId: 'user_amara',
        startsAt: '2026-08-18T11:30:00.000Z',
        endsAt: '2026-08-18T12:00:00.000Z',
        type: 'in-person',
        reason: 'Chest discomfort review',
        status: 'confirmed',
        createdAt: '2026-08-14T15:20:00.000Z',
      },
      {
        id: 'apt_leila_pending',
        patientId: 'user_leila',
        doctorId: 'user_amara',
        startsAt: '2026-08-18T14:00:00.000Z',
        endsAt: '2026-08-18T14:30:00.000Z',
        type: 'video',
        reason: 'New patient introduction',
        status: 'pending',
        createdAt: '2026-08-17T19:10:00.000Z',
      },
      {
        id: 'apt_sarah_past',
        patientId: 'user_sarah',
        doctorId: 'user_amara',
        startsAt: '2026-08-12T10:00:00.000Z',
        endsAt: '2026-08-12T10:30:00.000Z',
        type: 'video',
        reason: 'Medication review',
        status: 'completed',
        createdAt: '2026-08-01T10:00:00.000Z',
      },
      {
        id: 'apt_james_past',
        patientId: 'user_james',
        doctorId: 'user_amara',
        startsAt: '2026-08-04T09:30:00.000Z',
        endsAt: '2026-08-04T10:00:00.000Z',
        type: 'in-person',
        reason: 'ECG follow-up',
        status: 'completed',
        createdAt: '2026-07-20T10:00:00.000Z',
      },
      {
        id: 'apt_david_cancel',
        patientId: 'user_david',
        doctorId: 'user_chen',
        startsAt: '2026-08-05T11:00:00.000Z',
        endsAt: '2026-08-05T11:30:00.000Z',
        type: 'video',
        reason: 'Skin check',
        status: 'cancelled',
        createdAt: '2026-07-28T08:00:00.000Z',
      },
      {
        id: 'apt_amara_early',
        patientId: 'user_leila',
        doctorId: 'user_amara',
        startsAt: '2026-08-18T09:00:00.000Z',
        endsAt: '2026-08-18T09:30:00.000Z',
        type: 'video',
        reason: 'Blood pressure plan',
        status: 'completed',
        createdAt: '2026-08-10T08:00:00.000Z',
      },
    ],
    prescriptions: [
      {
        id: 'rx_metformin',
        patientId: 'user_david',
        doctorId: 'user_amara',
        medication: 'Metformin',
        dosage: '500 mg',
        frequency: 'Twice daily',
        startDate: '2026-08-12',
        endDate: '2026-11-12',
        refills: 2,
        instructions: 'Take with food. Record any persistent nausea.',
        status: 'active',
        createdAt: '2026-08-12T10:20:00.000Z',
      },
      {
        id: 'rx_lisinopril',
        patientId: 'user_david',
        doctorId: 'user_amara',
        medication: 'Lisinopril',
        dosage: '10 mg',
        frequency: 'Once daily',
        startDate: '2026-06-01',
        endDate: '2026-12-01',
        refills: 1,
        instructions: 'Take in the morning. Rise slowly from sitting.',
        status: 'active',
        createdAt: '2026-06-01T09:00:00.000Z',
      },
      {
        id: 'rx_sarah',
        patientId: 'user_sarah',
        doctorId: 'user_amara',
        medication: 'Atorvastatin',
        dosage: '20 mg',
        frequency: 'Once daily at night',
        startDate: '2026-08-12',
        endDate: '2026-11-12',
        refills: 3,
        instructions: 'Avoid grapefruit. Continue usual evening routine.',
        status: 'active',
        createdAt: '2026-08-12T10:40:00.000Z',
      },
      {
        id: 'rx_james',
        patientId: 'user_james',
        doctorId: 'user_amara',
        medication: 'Aspirin',
        dosage: '75 mg',
        frequency: 'Once daily',
        startDate: '2026-08-04',
        endDate: '2026-11-04',
        refills: 2,
        instructions: 'Take after breakfast.',
        status: 'active',
        createdAt: '2026-08-04T10:10:00.000Z',
      },
    ],
    notifications: [
      {
        id: 'nt_1',
        userId: 'user_david',
        kind: 'appointment',
        title: 'Appointment confirmed',
        body: 'Your visit with Dr. Okafor is set for tomorrow at 10:30.',
        createdAt: '2026-08-18T08:42:00.000Z',
        read: false,
      },
      {
        id: 'nt_2',
        userId: 'user_david',
        kind: 'prescription',
        title: 'Prescription renewed',
        body: 'Metformin was renewed. Two refills remain.',
        createdAt: '2026-08-18T07:15:00.000Z',
        read: false,
      },
      {
        id: 'nt_3',
        userId: 'user_david',
        kind: 'care-team',
        title: 'Message from your care team',
        body: 'Please keep a brief log of your morning blood pressure this week.',
        createdAt: '2026-08-17T16:20:00.000Z',
        read: true,
      },
      {
        id: 'nt_4',
        userId: 'user_amara',
        kind: 'appointment',
        title: 'New appointment',
        body: 'Sarah Miller booked Tuesday · 10:30.',
        createdAt: '2026-08-17T19:10:00.000Z',
        read: false,
      },
      {
        id: 'nt_5',
        userId: 'user_amara',
        kind: 'prescription',
        title: 'Prescription renewal requested',
        body: 'David Daniel asked about a Metformin refill.',
        createdAt: '2026-08-17T14:02:00.000Z',
        read: false,
      },
      {
        id: 'nt_6',
        userId: 'user_amara',
        kind: 'system',
        title: 'Your schedule was updated',
        body: 'Thursday afternoon hours were published.',
        createdAt: '2026-08-16T11:40:00.000Z',
        read: true,
      },
    ],
    audit: [
      {
        id: 'au_1',
        actorId: 'user_amara',
        actorName: 'Dr. Okafor',
        action: 'created a prescription for Sarah Miller',
        createdAt: '2026-08-18T12:32:00.000Z',
      },
      {
        id: 'au_2',
        actorId: 'user_david',
        actorName: 'David Daniel',
        action: 'booked an appointment with Dr. Okafor',
        createdAt: '2026-08-18T08:42:00.000Z',
      },
      {
        id: 'au_3',
        actorId: 'user_admin',
        actorName: 'Nora Ellis',
        action: 'updated doctor availability for Dr. Weber',
        createdAt: '2026-08-18T07:21:00.000Z',
      },
      {
        id: 'au_4',
        actorId: 'user_amara',
        actorName: 'Dr. Okafor',
        action: 'completed a consultation with Leila Hassan',
        createdAt: '2026-08-18T09:28:00.000Z',
      },
    ],
    notes: [
      {
        id: 'note_1',
        patientId: 'user_sarah',
        doctorId: 'user_amara',
        body: 'Tolerating statin well. Continue current dose and review lipids in 8 weeks.',
        createdAt: '2026-08-12T10:25:00.000Z',
      },
      {
        id: 'note_2',
        patientId: 'user_david',
        doctorId: 'user_amara',
        body: 'Home readings trending slightly high in the morning. Review technique and consider dose adjustment next visit.',
        createdAt: '2026-08-12T10:35:00.000Z',
      },
    ],
    passwordResets: [],
  }
}
